# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_JetTree')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_JetTree')
    _JetTree = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_JetTree', [dirname(__file__)])
        except ImportError:
            import _JetTree
            return _JetTree
        try:
            _mod = imp.load_module('_JetTree', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _JetTree = swig_import_helper()
    del swig_import_helper
else:
    import _JetTree
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _JetTree.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _JetTree.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _JetTree.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _JetTree.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _JetTree.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _JetTree.SwigPyIterator_equal(self, x)

    def copy(self):
        return _JetTree.SwigPyIterator_copy(self)

    def next(self):
        return _JetTree.SwigPyIterator_next(self)

    def __next__(self):
        return _JetTree.SwigPyIterator___next__(self)

    def previous(self):
        return _JetTree.SwigPyIterator_previous(self)

    def advance(self, n):
        return _JetTree.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _JetTree.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _JetTree.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _JetTree.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _JetTree.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _JetTree.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _JetTree.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _JetTree.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class PseudoJetVec(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PseudoJetVec, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PseudoJetVec, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _JetTree.PseudoJetVec_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _JetTree.PseudoJetVec___nonzero__(self)

    def __bool__(self):
        return _JetTree.PseudoJetVec___bool__(self)

    def __len__(self):
        return _JetTree.PseudoJetVec___len__(self)

    def __getslice__(self, i, j):
        return _JetTree.PseudoJetVec___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _JetTree.PseudoJetVec___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _JetTree.PseudoJetVec___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _JetTree.PseudoJetVec___delitem__(self, *args)

    def __getitem__(self, *args):
        return _JetTree.PseudoJetVec___getitem__(self, *args)

    def __setitem__(self, *args):
        return _JetTree.PseudoJetVec___setitem__(self, *args)

    def pop(self):
        return _JetTree.PseudoJetVec_pop(self)

    def append(self, x):
        return _JetTree.PseudoJetVec_append(self, x)

    def empty(self):
        return _JetTree.PseudoJetVec_empty(self)

    def size(self):
        return _JetTree.PseudoJetVec_size(self)

    def swap(self, v):
        return _JetTree.PseudoJetVec_swap(self, v)

    def begin(self):
        return _JetTree.PseudoJetVec_begin(self)

    def end(self):
        return _JetTree.PseudoJetVec_end(self)

    def rbegin(self):
        return _JetTree.PseudoJetVec_rbegin(self)

    def rend(self):
        return _JetTree.PseudoJetVec_rend(self)

    def clear(self):
        return _JetTree.PseudoJetVec_clear(self)

    def get_allocator(self):
        return _JetTree.PseudoJetVec_get_allocator(self)

    def pop_back(self):
        return _JetTree.PseudoJetVec_pop_back(self)

    def erase(self, *args):
        return _JetTree.PseudoJetVec_erase(self, *args)

    def __init__(self, *args):
        this = _JetTree.new_PseudoJetVec(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _JetTree.PseudoJetVec_push_back(self, x)

    def front(self):
        return _JetTree.PseudoJetVec_front(self)

    def back(self):
        return _JetTree.PseudoJetVec_back(self)

    def assign(self, n, x):
        return _JetTree.PseudoJetVec_assign(self, n, x)

    def resize(self, *args):
        return _JetTree.PseudoJetVec_resize(self, *args)

    def insert(self, *args):
        return _JetTree.PseudoJetVec_insert(self, *args)

    def reserve(self, n):
        return _JetTree.PseudoJetVec_reserve(self, n)

    def capacity(self):
        return _JetTree.PseudoJetVec_capacity(self)
    __swig_destroy__ = _JetTree.delete_PseudoJetVec
    __del__ = lambda self: None
PseudoJetVec_swigregister = _JetTree.PseudoJetVec_swigregister
PseudoJetVec_swigregister(PseudoJetVec)

class IntVec(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVec, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVec, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _JetTree.IntVec_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _JetTree.IntVec___nonzero__(self)

    def __bool__(self):
        return _JetTree.IntVec___bool__(self)

    def __len__(self):
        return _JetTree.IntVec___len__(self)

    def __getslice__(self, i, j):
        return _JetTree.IntVec___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _JetTree.IntVec___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _JetTree.IntVec___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _JetTree.IntVec___delitem__(self, *args)

    def __getitem__(self, *args):
        return _JetTree.IntVec___getitem__(self, *args)

    def __setitem__(self, *args):
        return _JetTree.IntVec___setitem__(self, *args)

    def pop(self):
        return _JetTree.IntVec_pop(self)

    def append(self, x):
        return _JetTree.IntVec_append(self, x)

    def empty(self):
        return _JetTree.IntVec_empty(self)

    def size(self):
        return _JetTree.IntVec_size(self)

    def swap(self, v):
        return _JetTree.IntVec_swap(self, v)

    def begin(self):
        return _JetTree.IntVec_begin(self)

    def end(self):
        return _JetTree.IntVec_end(self)

    def rbegin(self):
        return _JetTree.IntVec_rbegin(self)

    def rend(self):
        return _JetTree.IntVec_rend(self)

    def clear(self):
        return _JetTree.IntVec_clear(self)

    def get_allocator(self):
        return _JetTree.IntVec_get_allocator(self)

    def pop_back(self):
        return _JetTree.IntVec_pop_back(self)

    def erase(self, *args):
        return _JetTree.IntVec_erase(self, *args)

    def __init__(self, *args):
        this = _JetTree.new_IntVec(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _JetTree.IntVec_push_back(self, x)

    def front(self):
        return _JetTree.IntVec_front(self)

    def back(self):
        return _JetTree.IntVec_back(self)

    def assign(self, n, x):
        return _JetTree.IntVec_assign(self, n, x)

    def resize(self, *args):
        return _JetTree.IntVec_resize(self, *args)

    def insert(self, *args):
        return _JetTree.IntVec_insert(self, *args)

    def reserve(self, n):
        return _JetTree.IntVec_reserve(self, n)

    def capacity(self):
        return _JetTree.IntVec_capacity(self)
    __swig_destroy__ = _JetTree.delete_IntVec
    __del__ = lambda self: None
IntVec_swigregister = _JetTree.IntVec_swigregister
IntVec_swigregister(IntVec)

class DoubleVec(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVec, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVec, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _JetTree.DoubleVec_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _JetTree.DoubleVec___nonzero__(self)

    def __bool__(self):
        return _JetTree.DoubleVec___bool__(self)

    def __len__(self):
        return _JetTree.DoubleVec___len__(self)

    def __getslice__(self, i, j):
        return _JetTree.DoubleVec___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _JetTree.DoubleVec___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _JetTree.DoubleVec___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _JetTree.DoubleVec___delitem__(self, *args)

    def __getitem__(self, *args):
        return _JetTree.DoubleVec___getitem__(self, *args)

    def __setitem__(self, *args):
        return _JetTree.DoubleVec___setitem__(self, *args)

    def pop(self):
        return _JetTree.DoubleVec_pop(self)

    def append(self, x):
        return _JetTree.DoubleVec_append(self, x)

    def empty(self):
        return _JetTree.DoubleVec_empty(self)

    def size(self):
        return _JetTree.DoubleVec_size(self)

    def swap(self, v):
        return _JetTree.DoubleVec_swap(self, v)

    def begin(self):
        return _JetTree.DoubleVec_begin(self)

    def end(self):
        return _JetTree.DoubleVec_end(self)

    def rbegin(self):
        return _JetTree.DoubleVec_rbegin(self)

    def rend(self):
        return _JetTree.DoubleVec_rend(self)

    def clear(self):
        return _JetTree.DoubleVec_clear(self)

    def get_allocator(self):
        return _JetTree.DoubleVec_get_allocator(self)

    def pop_back(self):
        return _JetTree.DoubleVec_pop_back(self)

    def erase(self, *args):
        return _JetTree.DoubleVec_erase(self, *args)

    def __init__(self, *args):
        this = _JetTree.new_DoubleVec(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _JetTree.DoubleVec_push_back(self, x)

    def front(self):
        return _JetTree.DoubleVec_front(self)

    def back(self):
        return _JetTree.DoubleVec_back(self)

    def assign(self, n, x):
        return _JetTree.DoubleVec_assign(self, n, x)

    def resize(self, *args):
        return _JetTree.DoubleVec_resize(self, *args)

    def insert(self, *args):
        return _JetTree.DoubleVec_insert(self, *args)

    def reserve(self, n):
        return _JetTree.DoubleVec_reserve(self, n)

    def capacity(self):
        return _JetTree.DoubleVec_capacity(self)
    __swig_destroy__ = _JetTree.delete_DoubleVec
    __del__ = lambda self: None
DoubleVec_swigregister = _JetTree.DoubleVec_swigregister
DoubleVec_swigregister(DoubleVec)

class GhostSubtractor(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GhostSubtractor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GhostSubtractor, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _JetTree.new_GhostSubtractor(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def getDummies(self):
        return _JetTree.GhostSubtractor_getDummies(self)

    def getCorrectedJet(self, pseudojet):
        return _JetTree.GhostSubtractor_getCorrectedJet(self, pseudojet)
    __swig_destroy__ = _JetTree.delete_GhostSubtractor
    __del__ = lambda self: None
GhostSubtractor_swigregister = _JetTree.GhostSubtractor_swigregister
GhostSubtractor_swigregister(GhostSubtractor)

class SoftDropGroomer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SoftDropGroomer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SoftDropGroomer, name)
    __repr__ = _swig_repr

    def __init__(self, zcut=0.1, beta=0., r0=0.4):
        this = _JetTree.new_SoftDropGroomer(zcut, beta, r0)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def softdrop(self, j1, j2):
        return _JetTree.SoftDropGroomer_softdrop(self, j1, j2)

    def nsd(self):
        return _JetTree.SoftDropGroomer_nsd(self)

    def reset(self):
        return _JetTree.SoftDropGroomer_reset(self)
    __swig_destroy__ = _JetTree.delete_SoftDropGroomer
    __del__ = lambda self: None
SoftDropGroomer_swigregister = _JetTree.SoftDropGroomer_swigregister
SoftDropGroomer_swigregister(SoftDropGroomer)

class JetTree(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, JetTree, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, JetTree, name)
    __repr__ = _swig_repr

    def __init__(self, pseudojet, child=None, gs=None):
        this = _JetTree.new_JetTree(pseudojet, child, gs)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def pseudojet(self):
        return _JetTree.JetTree_pseudojet(self)

    def harder(self):
        return _JetTree.JetTree_harder(self)

    def softer(self):
        return _JetTree.JetTree_softer(self)

    def child(self):
        return _JetTree.JetTree_child(self)

    def swap(self):
        return _JetTree.JetTree_swap(self)

    def has_structure(self):
        return _JetTree.JetTree_has_structure(self)

    def remove_soft(self, do_recursive_correction=False):
        return _JetTree.JetTree_remove_soft(self, do_recursive_correction)

    def e1(self):
        return _JetTree.JetTree_e1(self)

    def e2(self):
        return _JetTree.JetTree_e2(self)

    def pt1(self):
        return _JetTree.JetTree_pt1(self)

    def pt2(self):
        return _JetTree.JetTree_pt2(self)

    def eta1(self):
        return _JetTree.JetTree_eta1(self)

    def eta2(self):
        return _JetTree.JetTree_eta2(self)

    def phi1(self):
        return _JetTree.JetTree_phi1(self)

    def phi2(self):
        return _JetTree.JetTree_phi2(self)

    def z(self):
        return _JetTree.JetTree_z(self)

    def delta(self):
        return _JetTree.JetTree_delta(self)

    def kperp(self):
        return _JetTree.JetTree_kperp(self)

    def groom(self, groomer, do_recursive_correction=False):
        return _JetTree.JetTree_groom(self, groomer, do_recursive_correction)

    def zg(self, groomer):
        return _JetTree.JetTree_zg(self, groomer)

    def deltag(self, groomer):
        return _JetTree.JetTree_deltag(self, groomer)

    def hello_world(self):
        return _JetTree.JetTree_hello_world(self)

    def show(self):
        return _JetTree.JetTree_show(self)
    __swig_destroy__ = _JetTree.delete_JetTree
    __del__ = lambda self: None
JetTree_swigregister = _JetTree.JetTree_swigregister
JetTree_swigregister(JetTree)

# This file is compatible with both classic and new-style classes.


